Repository bounswe/bounswe2020group1, pull requests merged in 2020-05, with the labels that each got.

#120 352 - Practice App - API - Frontend - Home Page
  API/FrontEnd/home.html
Labels: priority:high, status:in-progress, type:implementation

#130 HTML page for creating new products
  API/FrontEnd/createP.html
Labels: priority:urgent, status:completed

#124 352 - Practice App - API - Frontend - Product Page
  API/FrontEnd/product_page.html
Labels: priority:high, status:in-progress, type:implementation

#112 Practice App: Search endpoint
  practice_app/backend/flaskr/routes_search.py
Labels: type:code-review
